apiVersion: v1
kind: Namespace
metadata:
  name: liatrio-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-app
  namespace: liatrio-namespace
spec:
  selector:
    matchLabels:
      app: liatrio-app
  template:
    metadata:
      labels:
        app: liatrio-app
    spec:
      containers:
      - name: liatrio-app
        image: cshoffner/liatrio_exercise:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
          requests: 
            memory: "250Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: liatrio-app
  namespace: liatrio-namespace
spec:
  selector:
    app: liatrio-app
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
