name: test-python

on: 
  workflow_dispatch:
    

jobs: 
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.8'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute script
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: python get_outputs.py
      - name: print
        run: echo ${{ env.CLUSTER_NAME }}